# Generated by Django 4.0.1 on 2022-01-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_medicine_finch_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='medicine',
            new_name='medicines',
        ),
    ]
